{% set name = "rechunker" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e0e6620b00d5c1688f16a22beb2ec1d10c37742a36fcec8e9b184591e5b30e7a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - python >=3.6
    - dask
    - zarr
    - xarray

test:
  imports:
    - rechunker
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://rechunker.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Disk-to-disk chunk transformation for chunked arrays.
  description: |
    Rechunker is a Python package which enables efficient and scalable
    manipulation of the chunk structure of chunked array formats such as Zarr
    and TileDB. Rechunker takes an input array (or group of arrays) stored in a
    persistent storage device (such as a filesystem or a cloud storage bucket)
    and writes out an array (or group of arrays) with the same data, but
    different chunking scheme, to a new location.
    Rechunker is designed to be used within a parallel execution framework such as Dask.
  dev_url: https://github.com/pangeo-data/rechunker

extra:
  recipe-maintainers:
    - davidbrochart
    - TomAugspurger
    - rabernat
