{% set name = "rechunker" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 18c610cc65854b3627c4d511138a7b962281f8e00838f78148cbf765e1ba2fb2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm
  run:
    - dask-core
    - python >=3.8
    - zarr >=2.11
    - mypy_extensions
    - dask
    # dask[array]
    - numpy >=1.21
    # dask[diagnostics]
    - bokeh >=2.4.2, <3
    - jinja2 >=2.10.3
    # extras but not all of the complete!?
    - xarray >=2022.3

test:
  imports:
    - rechunker
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://rechunker.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Disk-to-disk chunk transformation for chunked arrays.
  description: |
    Rechunker is a Python package which enables efficient and scalable
    manipulation of the chunk structure of chunked array formats such as Zarr
    and TileDB. Rechunker takes an input array (or group of arrays) stored in a
    persistent storage device (such as a filesystem or a cloud storage bucket)
    and writes out an array (or group of arrays) with the same data, but
    different chunking scheme, to a new location.
    Rechunker is designed to be used within a parallel execution framework such as Dask.
  dev_url: https://github.com/pangeo-data/rechunker

extra:
  recipe-maintainers:
    - davidbrochart
    - TomAugspurger
    - rabernat
    - ocefpaf
    - rsignell-usgs
